[0m23:23:27.271442 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3856BE570>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3856BE690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3856BE6C0>]}


============================== 23:23:27.289487 | 577e6153-a97f-4f65-bcf5-ab336f1c4eb0 ==============================
[0m23:23:27.289487 [info ] [MainThread]: Running with dbt=1.7.13
[0m23:23:27.290491 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Huy Hoang\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:23:38.790234 [debug] [MainThread]: Starter project path: C:\Users\Huy Hoang\Desktop\dbt_workspace\dbt_venv\Lib\site-packages\dbt\include\starter_project
[0m23:23:38.824057 [info ] [MainThread]: 
Your new dbt project "dbt_test" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m23:23:38.827058 [info ] [MainThread]: Setting up your profile.
[0m23:24:23.875564 [info ] [MainThread]: Profile dbt_test written to C:\Users\Huy Hoang\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m23:24:23.878572 [debug] [MainThread]: Command `dbt init` succeeded at 23:24:23.877572 after 56.71 seconds
[0m23:24:23.878572 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E38556FA40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3857835C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E385259EE0>]}
[0m23:24:23.879572 [debug] [MainThread]: Flushing usage events
[0m23:33:10.264978 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C10697DE80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C10697D760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C10697C830>]}


============================== 23:33:10.269980 | bf5cd6c4-06a5-4d33-9974-9da1afd0107d ==============================
[0m23:33:10.269980 [info ] [MainThread]: Running with dbt=1.7.13
[0m23:33:10.270978 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Huy Hoang\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:33:10.270978 [info ] [MainThread]: dbt version: 1.7.13
[0m23:33:10.272012 [info ] [MainThread]: python version: 3.12.3
[0m23:33:10.272980 [info ] [MainThread]: python path: C:\Users\Huy Hoang\Desktop\dbt_workspace\dbt_venv\Scripts\python.exe
[0m23:33:10.273977 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m23:33:10.386182 [info ] [MainThread]: Using profiles dir at C:\Users\Huy Hoang\.dbt
[0m23:33:10.387217 [info ] [MainThread]: Using profiles.yml file at C:\Users\Huy Hoang\.dbt\profiles.yml
[0m23:33:10.388179 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Huy Hoang\Desktop\dbt_workspace\dbt_project.yml
[0m23:33:10.390727 [info ] [MainThread]: adapter type: postgres
[0m23:33:10.391742 [info ] [MainThread]: adapter version: 1.7.13
[0m23:33:10.392737 [info ] [MainThread]: Configuration:
[0m23:33:10.393744 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m23:33:10.394740 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m23:33:10.395739 [info ] [MainThread]: Required dependencies:
[0m23:33:10.396740 [debug] [MainThread]: Executing "git --help"
[0m23:33:10.400739 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m23:33:10.402029 [info ] [MainThread]: Connection:
[0m23:33:10.403038 [info ] [MainThread]:   host: localhost
[0m23:33:10.404038 [info ] [MainThread]:   port: 32117
[0m23:33:10.405038 [info ] [MainThread]:   user: thh
[0m23:33:10.405038 [info ] [MainThread]:   database: postdb
[0m23:33:10.407073 [info ] [MainThread]:   schema: public
[0m23:33:10.407578 [info ] [MainThread]:   connect_timeout: 10
[0m23:33:10.408654 [info ] [MainThread]:   role: None
[0m23:33:10.409666 [info ] [MainThread]:   search_path: None
[0m23:33:10.410662 [info ] [MainThread]:   keepalives_idle: 0
[0m23:33:10.411662 [info ] [MainThread]:   sslmode: None
[0m23:33:10.411662 [info ] [MainThread]:   sslcert: None
[0m23:33:10.412669 [info ] [MainThread]:   sslkey: None
[0m23:33:10.414871 [info ] [MainThread]:   sslrootcert: None
[0m23:33:10.415871 [info ] [MainThread]:   application_name: dbt
[0m23:33:10.416869 [info ] [MainThread]:   retries: 1
[0m23:33:10.418299 [info ] [MainThread]: Registered adapter: postgres=1.7.13
[0m23:33:10.420650 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m23:33:10.420650 [debug] [MainThread]: Using postgres connection "debug"
[0m23:33:10.421651 [debug] [MainThread]: On debug: select 1 as id
[0m23:33:10.421651 [debug] [MainThread]: Opening a new connection, currently in state init
[0m23:33:14.520269 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "localhost" (::1), port 32117 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 32117 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?

[0m23:33:18.588129 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m23:33:18.591209 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m23:33:18.592208 [debug] [MainThread]: On debug: No close available on handle
[0m23:33:18.594209 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m23:33:18.596203 [info ] [MainThread]: [31m3 checks failed:[0m
[0m23:33:18.598194 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Huy Hoang\Desktop\dbt_workspace\dbt_project.yml> not found

[0m23:33:18.600194 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m23:33:18.602197 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  connection to server at "localhost" (::1), port 32117 failed: Connection refused (0x0000274D/10061)
  	Is the server running on that host and accepting TCP/IP connections?
  connection to server at "localhost" (127.0.0.1), port 32117 failed: Connection refused (0x0000274D/10061)
  	Is the server running on that host and accepting TCP/IP connections?
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m23:33:18.607389 [debug] [MainThread]: Command `dbt debug` failed at 23:33:18.606375 after 8.46 seconds
[0m23:33:18.608385 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m23:33:18.609387 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C106545400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C10695BE60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C10695BB90>]}
[0m23:33:18.610386 [debug] [MainThread]: Flushing usage events
